"use client";
import {useMemo,useState} from "react";
import {Search,Building2,ShieldCheck,MapPin,CalendarDays,Landmark,FileText,AlertTriangle} from "lucide-react";
import {realContracts,contractSource} from "@/data/realContracts";
const norm=s=>(s||"").toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").trim();
const dist=(a,b)=>{a=norm(a);b=norm(b);const m=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return m[a.length][b.length]};
export default function ContractorSearch(){
 const [q,setQ]=useState(""),[selected,setSelected]=useState("");
 const groups=useMemo(()=>{const m={};realContracts.forEach(c=>{const k=norm(c.contractor).replace(/\b(inc|ltd|limited|company|co)\b/g,"").trim();(m[k]??=[]).push(c)});return Object.entries(m).map(([key,rows])=>({key,name:rows[0].contractor,rows,total:rows.reduce((a,x)=>a+(x.currency==="G$"?x.amount:0),0),agencies:new Set(rows.map(x=>x.agency)).size,regions:new Set(rows.map(x=>x.region).filter(x=>!x.startsWith("Not "))).size}));},[]);
 const matches=useMemo(()=>{if(!q.trim())return groups;const nq=norm(q);return groups.map(g=>({...g,score:norm(g.name).includes(nq)?0:dist(nq,g.name)})).filter(g=>g.score===0||g.score<=Math.max(3,Math.floor(nq.length*.35))).sort((a,b)=>a.score-b.score)},[q,groups]);
 const g=groups.find(x=>x.key===selected)||matches[0]||groups[0];
 return <section className="realContractors"><div className="contractorHero"><div><span className="eyebrow green">PUBLIC CONTRACTOR SEARCH · LIVE-SOURCE REPOSITORY</span><h1>Government Contractor Search</h1><p>Search identified government contract awards by contractor or company name. Minor misspellings are supported.</p></div><div className="verifiedBadge"><ShieldCheck size={14}/> SOURCE-BACKED PUBLIC RECORDS</div></div>
 <div className="contractSearch"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Type contractor name — minor misspellings are okay"/></div>
 <div className="contractorGrid"><div className="panel contractorNames"><h3><Building2/> Contractors / companies <span>{matches.length}</span></h3>{matches.map(x=><button className={g?.key===x.key?"selected":""} key={x.key} onClick={()=>setSelected(x.key)}><strong>{x.name}</strong><span>{x.rows.length} identified award{x.rows.length!==1?"s":""} · G${(x.total/1e6).toFixed(2)}M</span><small>Records found: {Math.min(...x.rows.map(r=>r.year))}–{Math.max(...x.rows.map(r=>r.year))}</small></button>)}</div>
 {g&&<div><div className="panel contractorProfile"><div className="profileHead"><div><small>VERIFIED NPTA AWARDEE</small><h2>{g.name}</h2><span>Canonical contractor profile generated from identified NPTA award records</span></div><div><small>PUBLIC RECORD COVERAGE</small><strong>IDENTIFIED RECORDS</strong></div></div>
 <div className="contractMetrics"><div><strong>{g.rows.length}</strong><span>Identified awards</span></div><div><strong>G${(g.total/1e6).toFixed(2)}M</strong><span>Disclosed G$ value</span></div><div><strong>{g.agencies}</strong><span>Awarding entities</span></div><div><strong>{g.regions||"—"}</strong><span>Explicit regions</span></div></div>
 <div className="contractTable"><div className="ctHead"><span>Contract / Project</span><span>Agency</span><span>Value</span><span>Award date</span><span>Method</span></div>{g.rows.map(r=><div className="ctRow" key={r.id}><div><strong>{r.description}</strong><small>{r.id} · {r.region}</small></div><span>{r.agency}</span><b>{r.currency}{r.amount.toLocaleString()}</b><span>{r.awardDate}</span><em>{r.method}</em></div>)}</div></div>
 <div className="panel contractEvidence"><h3><FileText/> Contract evidence</h3>{g.rows.map(r=><div key={r.id}><div><strong>{r.id}</strong><span>{r.description}</span></div><div><span><Landmark/> {r.agency}</span><span><CalendarDays/> Awarded {r.awardDate}</span><span><MapPin/> {r.region}</span></div><small>{r.tenders} tender/proposal record · uploaded {r.uploadDate} · Source: {contractSource}</small></div>)}</div>
 <div className="coverageNote"><AlertTriangle/><span><strong>Coverage note:</strong> This profile contains awards actually identified in the loaded NPTA source-backed repository. It does not claim to represent every contract the contractor has ever received. Additional records will appear as historical ingestion expands.</span></div></div>}</div></section>
}