"use client";
import {useMemo,useState} from "react"; import {Search,Building2,FileText,Landmark,ShieldCheck} from "lucide-react";
import {contractors,contractHistory} from "@/data/contractors"; import {searchContractors} from "@/utils/fuzzyContractor";
import {linksForContractor} from "@/data/connectedRecords";
export default function ContractorSearch({executive=false}){
 const [query,setQuery]=useState(""),[selected,setSelected]=useState(contractors[0]),[year,setYear]=useState("All");
 const results=useMemo(()=>searchContractors(contractors,query),[query]);
 const contracts=contractHistory.filter(x=>x.contractor===selected.id&&(year==="All"||x.year===Number(year)));
 const linkedProjects=linksForContractor(selected.id);
 return <section><div className="contractorIntro"><div><span className="eyebrow green">{executive?"EXECUTIVE CONTRACTOR INTELLIGENCE":"PUBLIC CONTRACTOR SEARCH"}</span><h2>{executive?"Contractor Intelligence":"Government Contractor Search"}</h2><p>{executive?"Research government award history, concentration and linked platform evidence.":"Search sourced government contract records by contractor or company name."}</p></div>{!executive&&<div className="publicBadge"><ShieldCheck size={15}/> SOURCE-BACKED PUBLIC RECORDS</div>}</div>
 <div className="contractorSearchHero"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Type contractor name — minor misspellings are okay"/>{query&&<span>{results.length} possible matches</span>}</div>
 <div className={executive?"contractorLayout":"contractorLayout public"}><div className="panel contractorResults"><div className="contractorSectionTitle"><Building2 size={16}/><strong>Contractors / companies</strong></div>{results.length?results.map(c=><button key={c.id} onClick={()=>setSelected(c)} className={selected.id===c.id?"contractorResult selected":"contractorResult"}><div><strong>{c.name}</strong>{c.label&&<b>{c.label} · {Math.round(c.match*100)}%</b>}</div><span>{c.contracts} identified contracts · {c.total}</span><small>Records found: {c.first}–{c.latest}</small></button>):<div className="noContractor"><strong>No close match found</strong><span>Try fewer words or a different spelling.</span></div>}</div>
 <div className="contractorMain"><div className="panel contractorProfile"><div className="profileTop"><div><span className="eyebrow">{selected.id}</span><h3>{selected.name}</h3><p>Known aliases: {selected.aliases.join(" · ")}</p></div><div className="sourceCoverage"><span>PUBLIC RECORD COVERAGE</span><strong>{selected.first}–{selected.latest}</strong></div></div><div className="contractorStats"><div><strong>{selected.contracts}</strong><span>Identified contracts</span></div><div><strong>{selected.total}</strong><span>Disclosed award value</span></div><div><strong>{selected.agencies}</strong><span>Awarding entities</span></div><div><strong>{selected.regions}</strong><span>Regions</span></div></div>
 <div className="contractFilters"><label>Year<select value={year} onChange={e=>setYear(e.target.value)}><option>All</option>{[2026,2025,2024,2023,2022,2021].map(x=><option key={x}>{x}</option>)}</select></label><span>{contracts.length} displayed records</span></div><div className="contractTable"><div className="contractTableHead"><span>Contract / Project</span><span>Agency</span><span>Value</span><span>Year</span><span>Status</span></div>{contracts.map(x=><div className="contractRow" key={x.id}><div><strong>{x.title}</strong><small>{x.id} · {x.region}</small></div><span>{x.agency}</span><b>{x.value}</b><span>{x.year}</span><em>{x.status}</em></div>)}</div></div>
 {linkedProjects.length>0&&<div className="panel contractorProjects"><div className="contractorSectionTitle"><Landmark size={16}/><strong>Connected projects & promises</strong></div>{linkedProjects.map(x=><div className="linkedProjectRow" key={x.id}><div><strong>{x.project}</strong><span>{x.projectId} · {x.region} · {x.status}</span></div><div><span>Government promise</span><strong>{x.promise}</strong></div><div><span>Contract</span><strong>{x.contractId} · {x.value}</strong></div></div>)}</div>}
 <div className="publicMethod"><ShieldCheck size={16}/><p><strong>Coverage note:</strong> contract history means records successfully identified from available public sources. It does not guarantee every historical government contract has been digitized or captured.</p></div></div>
 {executive&&<aside className="panel contractorExecutive"><div className="contractorSectionTitle"><Landmark size={16}/><strong>Executive analysis</strong></div><div className="execContractStat"><span>UNRESOLVED REPORTS LINKED TO TRACKED PROJECTS</span><strong>{selected.unresolved}</strong><small>Geographic/project association only</small></div><div className="execContractStat"><span>RESEARCH STATUS</span><strong>{selected.risk}</strong></div><div className="contractSignal"><span>AI RESEARCH SIGNAL</span><p>Compare award frequency, value and procuring entities over time. Treat unusual patterns as research leads, not allegations.</p></div><button className="contractBrief"><FileText size={14}/> Build contractor research brief</button></aside>}</div></section>
}