"use client";
import {useMemo,useState} from "react";
import {ShieldCheck,ExternalLink,CheckCircle2,Clock3,AlertTriangle,Search} from "lucide-react";
import {historicalCoverage} from "@/data/historicalCoverage";
import {backfillQueue} from "@/data/backfillQueue";
import {unifiedProjects} from "@/data/unifiedProjects";
import {realContracts} from "@/data/realContracts";
export default function DataCoverageCenter(){
 const [q,setQ]=useState("");
 const rows=useMemo(()=>historicalCoverage.filter(x=>String(x.year).includes(q.trim())),[q]);
 const pYears=new Set(unifiedProjects.map(x=>x.year));
 return <section className="coverageCenter"><div className="coverageHero"><div><span className="eyebrow green">HISTORICAL DATA INGESTION</span><h1>Repository Coverage Center</h1><p>See what Guyana Watch has actually ingested, which official sources are available, and which years still require historical backfill.</p></div><div className="verifiedBadge"><ShieldCheck size={14}/> TRANSPARENT COVERAGE</div></div>
 <div className="coverageSummary"><div><strong>2012–2026</strong><span>Target historical range</span></div><div><strong>{unifiedProjects.length}</strong><span>Project / budget records loaded</span></div><div><strong>{realContracts.length}</strong><span>Contract awards loaded</span></div><div><strong>{pYears.size} / 15</strong><span>Years with project records</span></div></div>
 <div className="coverageRule"><AlertTriangle/><div><strong>A source being available does not mean the year has been ingested.</strong><span>A year is marked loaded only when individual records have actually been extracted, normalized and stored.</span></div></div>
 <div className="coverageSearch"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter by year"/></div>
 <div className="panel coverageTable"><div className="covHead"><span>Year</span><span>Projects / budgets</span><span>Contracts</span><span>Official source status</span><span>Next action</span></div>{rows.sort((a,b)=>b.year-a.year).map(r=><div className="covRow" key={r.year}><strong>{r.year}</strong><div><b>{r.projects}</b><small>{r.projects?"records loaded":"Backfill pending"}</small></div><div><b>{r.contracts}</b><small>{r.contracts?"awards loaded":"Backfill pending"}</small></div><div className="sourceLocated"><CheckCircle2/><span>Budget archive located</span></div><div>{r.projects&&r.contracts?<span className="covDone">Continue expansion</span>:<span className="covPending"><Clock3/> Extract & verify</span>}</div></div>)}</div>
 <div className="coverageSources"><div className="panel"><h3>Official project / budget source</h3><p>Guyana Ministry of Finance Budget Estimates archive. Historical editions contain the capital-project profiles used by Projects & Promises.</p><a href="https://finance.gov.gy/budget/budget-estimates/" target="_blank" rel="noreferrer">Open Ministry of Finance archive <ExternalLink/></a></div><div className="panel"><h3>Official contract source</h3><p>National Procurement and Tender Administration awarded-contract records used for verified contractor and award relationships.</p><a href="https://www.npta.gov.gy/tenders-awarded/" target="_blank" rel="noreferrer">Open NPTA awarded contracts <ExternalLink/></a></div></div>
 <div className="backfillQueue"><div className="queueTitle"><div><span className="eyebrow green">PHASE 7.8</span><h2>2022–2023 Backfill Queue</h2><p>Official Volume 3 capital-project sources are verified and queued for record-level extraction. No project is counted as loaded until its fields have actually been parsed and stored.</p></div></div><div className="queueGrid">{backfillQueue.map(x=><div className="panel queueCard" key={x.year}><div className="queueYear">{x.year}</div><div><strong>{x.source}</strong><span>{x.type}</span><small>{x.status} · {x.ingestion}</small></div><a href={x.url} target="_blank" rel="noreferrer">Open official source <ExternalLink/></a></div>)}</div><div className="queueRule"><ShieldCheck/><span><b>Publication rule:</b> extracted records remain classified as BUDGET / PROJECT. Contractor and contract-award fields stay empty unless a separate verified procurement source establishes that relationship.</span></div></div><div className="ingestionPipeline"><h3>Historical ingestion workflow</h3><div><span>1</span><b>Locate official annual source</b><em>Budget estimates, procurement records and official releases</em></div><div><span>2</span><b>Extract individual records</b><em>Project, agency, value, geography, dates and identifiers</em></div><div><span>3</span><b>Normalize & deduplicate</b><em>Standardize money, names, locations and repeated projects</em></div><div><span>4</span><b>Match relationships</b><em>Budget/project → tender → award → contractor only where evidence supports it</em></div><div><span>5</span><b>Publish with provenance</b><em>Classification, coverage status and original-source link retained</em></div></div></section>
}