"use client";
import {useMemo,useState} from "react";
import {formatGYDFromMillions} from "@/utils/money"; import {Archive,Search,ShieldCheck,FileText,Building2,WalletCards,AlertTriangle} from "lucide-react"; import {historical2012} from "@/data/historical2012";
export default function HistoricalRepository(){
 const [q,setQ]=useState(""),[agency,setAgency]=useState("All");
 const agencies=["All",...new Set(historical2012.map(x=>x.agency))];
 const rows=useMemo(()=>historical2012.filter(x=>(agency==="All"||x.agency===agency)&&(`${x.title} ${x.agency} ${x.description} ${x.project_code}`.toLowerCase().includes(q.toLowerCase()))),[q,agency]);
 const total=rows.reduce((a,x)=>a+x.amount_m_gyd,0);
 return <section>
  <div className="historyIntro"><div><span className="eyebrow green">HISTORICAL REPOSITORY · REAL SOURCE-BACKED STARTER DATA</span><h2>2012 Government Projects & Budget Records</h2><p>The historical repository now contains verified 2012 records extracted from official Ministry of Finance material. These are budget/project records—not contract-award records unless a contract source separately confirms an award.</p></div><div className="historyBadge"><ShieldCheck size={14}/> VERIFIED 2012 SOURCE RECORDS</div></div>
  <div className="historyWarning"><AlertTriangle size={14}/><p><strong>Data distinction:</strong> a budget allocation or announced project does not identify the contractor. Contractor fields remain blank until an award/procurement source provides that information.</p></div>
  <div className="historyStats"><div><Archive/><span><strong>{historical2012.length}</strong><small>Starter 2012 records loaded</small></span></div><div><WalletCards/><span><strong>{formatGYDFromMillions(historical2012.reduce((a,x)=>a+x.amount_m_gyd,0))}</strong><small>Value represented in loaded records</small></span></div><div><Building2/><span><strong>{new Set(historical2012.map(x=>x.agency)).size}</strong><small>Government entities represented</small></span></div><div><FileText/><span><strong>Official</strong><small>Ministry of Finance source</small></span></div></div>
  <div className="historyTools"><div><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search 2012 project, programme, agency or code"/></div><select value={agency} onChange={e=>setAgency(e.target.value)}>{agencies.map(a=><option key={a}>{a}</option>)}</select><span>{rows.length} records · {formatGYDFromMillions(total)} represented</span></div>
  <div className="panel historyTable"><div className="historyHead"><span>Project / Programme</span><span>Agency</span><span>2012 Budget</span><span>Type</span><span>Source</span></div>{rows.map(x=><div className="historyRow" key={x.id}><div><strong>{x.title}</strong><small>{x.project_code} · {x.description}</small></div><span>{x.agency}</span><b>{formatGYDFromMillions(x.amount_m_gyd)}</b><em>{x.type}</em><div><strong>{x.source}</strong><small>PDF page {x.source_page} · {x.coverage}</small></div></div>)}</div>
  <div className="historyCoverage"><strong>2012 coverage status: PARTIAL / EXPANDING</strong><span>This is the first verified batch, not the complete 2012 budget. The ingestion process should continue across all 2012 estimate volumes, budget speeches, official project records and any available procurement archives.</span></div>
 </section>
}