"use client";
import {useState} from "react"; import {Bot,Database,FileSearch,Link2,RefreshCw,ShieldCheck,PlusCircle,CheckCircle2,XCircle,ExternalLink} from "lucide-react"; import {sources,candidates,pipeline} from "@/data/intelligence"; import ManualProjectEntry from "@/components/ManualProjectEntry";
import ConnectedDataView from "@/components/ConnectedDataView";
import LiveDataFoundation from "@/components/LiveDataFoundation";
import NptaIngestion from "@/components/NptaIngestion";
export default function IntelligenceCenter(){
 const [manual,setManual]=useState(false),[selected,setSelected]=useState(candidates[0]);
 const [mode,setMode]=useState("Extraction");
 return <section><div className="intelIntro"><div><span className="eyebrow green">PHASE 5.1 · AUTOMATED GOVERNMENT INTELLIGENCE</span><h2>Source & Extraction Center</h2><p>Discover records automatically, match them to existing projects, then require human review before publication.</p></div><button className="manualEntryBtn" onClick={()=>setManual(true)}><PlusCircle size={15}/> Manual entry</button></div>
 <div className="intelModeTabs"><button className={mode==="Extraction"?"active":""} onClick={()=>setMode("Extraction")}>Extraction Queue</button><button className={mode==="Connected"?"active":""} onClick={()=>setMode("Connected")}>Connected Records</button><button className={mode==="System"?"active":""} onClick={()=>setMode("System")}>Data Pipeline</button><button className={mode==="NPTA"?"active":""} onClick={()=>setMode("NPTA")}>NPTA Ingestion</button></div>
 {mode==="NPTA"?<NptaIngestion/>:mode==="System"?<LiveDataFoundation/>:mode==="Connected"?<ConnectedDataView/>:<>
 <div className="pipelineMetrics">{pipeline.map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div>
 <div className="intelLayout"><div className="panel sourcePanel"><div className="intelSectionTitle"><Database size={16}/><strong>Monitored sources</strong><button><RefreshCw size={12}/> Scan</button></div>{sources.map(s=><div className="sourceRow" key={s.id}><div className="sourceIcon"><FileSearch size={16}/></div><div><strong>{s.name}</strong><span>{s.coverage}</span><small>{s.type} · {s.tier} · Last check: {s.last}</small></div><b>{s.status}</b></div>)}<div className="sourceRule"><ShieldCheck size={16}/><p><strong>Source rule:</strong> official records are primary evidence. Media can discover, corroborate or challenge a record but does not silently overwrite official-source fields.</p></div></div>
 <div className="panel extractionQueue"><div className="intelSectionTitle"><Bot size={16}/><strong>AI extraction queue</strong><span>Human approval required</span></div>{candidates.map(c=><button key={c.id} className={selected.id===c.id?"candidate selected":"candidate"} onClick={()=>setSelected(c)}><div className="candidateTop"><span>{c.id} · {c.kind}</span><b>{c.confidence}% confidence</b></div><strong>{c.title}</strong><small>{c.source}</small><div><span>{c.region}</span><span>{c.match}</span></div></button>)}</div>
 <aside className="panel candidateReview"><div className="reviewHead"><span className="eyebrow">{selected.id}</span><h3>{selected.title}</h3><p>{selected.source}</p></div><div className="confidenceBox"><Bot size={19}/><div><span>Extraction confidence</span><strong>{selected.confidence}%</strong></div></div><div className="extractedFields"><div><span>Record type</span><strong>{selected.kind}</strong></div><div className="contractorExtract"><span>CONTRACTOR / AWARDEE</span><strong>{selected.contractor||"Not identified in source"}</strong></div><div><span>Region</span><strong>{selected.region}</strong></div><div><span>Amount</span><strong>{selected.amount}</strong></div><div><span>Deadline</span><strong>{selected.deadline}</strong></div><div><span>Project match</span><strong>{selected.match}</strong></div></div><div className="propagationBox"><span>ON APPROVAL, UPDATE CONNECTED RECORDS</span><div><b>Projects & Promises</b><b>Contractor Profile</b><b>Contract History</b><b>Executive Intelligence</b></div><p>Approved extracted fields are written once to the canonical record and become available across connected views. Missing fields remain “Not provided” until another verified source supplies them.</p></div>
<div className="matchingNote"><Link2 size={16}/><p>AI suggestions never establish causation by themselves. Staff confirms whether this source belongs to an existing project, creates a new record, or rejects the match.</p></div><label className="reviewNotes">Reviewer notes<textarea rows="4" placeholder="Add verification notes…"/></label><div className="candidateActions"><button className="rejectCandidate"><XCircle size={14}/> Reject</button><button className="approveCandidate"><CheckCircle2 size={14}/> Approve to project record</button></div></aside></div>
 <div className="automationFlow"><div><strong>1</strong><span>Source discovered</span></div><i>→</i><div><strong>2</strong><span>AI extracts fields</span></div><i>→</i><div><strong>3</strong><span>Duplicate/project match</span></div><i>→</i><div><strong>4</strong><span>Staff verifies</span></div><i>→</i><div><strong>5</strong><span>Project timeline updated</span></div></div>
 </>}
 <ManualProjectEntry open={manual} onClose={()=>setManual(false)}/></section>
}