"use client";
import {useState} from "react";
import {Database,RefreshCw,Server,ShieldCheck,GitMerge,Clock3,CheckCircle2,AlertTriangle,FileSearch,ArrowRight,LockKeyhole} from "lucide-react";
import {liveSources,ingestionRuns,canonicalFields} from "@/data/liveSources";

export default function LiveDataFoundation(){
 const [tab,setTab]=useState("Pipeline");
 return <section>
  <div className="liveIntro"><div><span className="eyebrow green">PHASE 7 · LIVE DATA FOUNDATION</span><h2>Data Pipeline & System Foundation</h2><p>Define how real government and media records enter the platform, become canonical records and propagate safely across every connected view.</p></div><div className="foundationBadge"><Server size={15}/> BACKEND-READY ARCHITECTURE</div></div>
  <div className="foundationNotice"><AlertTriangle size={16}/><div><strong>Connection boundary</strong><span>This phase builds the production data architecture and operator controls. External source adapters still require deployment credentials, persistent database infrastructure and scheduled server jobs before they can fetch live records.</span></div></div>
  <div className="liveTabs"><button className={tab==="Pipeline"?"active":""} onClick={()=>setTab("Pipeline")}>Ingestion Pipeline</button><button className={tab==="Schema"?"active":""} onClick={()=>setTab("Schema")}>Canonical Data Model</button><button className={tab==="Runs"?"active":""} onClick={()=>setTab("Runs")}>Run History</button></div>
  {tab==="Pipeline"&&<><div className="sourceAdapters">{liveSources.map(s=><div className="panel sourceAdapter" key={s.id}><div className="adapterTop"><div><b>{s.short}</b><span>{s.type}</span></div><em>{s.health}</em></div><h3>{s.name}</h3><div className="adapterMeta"><span><Clock3/> {s.cadence}</span><span><RefreshCw/> {s.mode}</span></div><div className="fieldTags">{s.fields.map(x=><i key={x}>{x}</i>)}</div><div className="adapterDest"><span>Writes to</span><strong>{s.destination.join(" · ")}</strong></div></div>)}</div>
  <div className="pipelineArchitecture"><div><FileSearch/><strong>1. Acquire</strong><span>Official document / article</span></div><ArrowRight/><div><Database/><strong>2. Extract</strong><span>Structured source fields</span></div><ArrowRight/><div><GitMerge/><strong>3. Resolve</strong><span>Project, contractor, agency matching</span></div><ArrowRight/><div><ShieldCheck/><strong>4. Verify</strong><span>Human review when required</span></div><ArrowRight/><div><Server/><strong>5. Publish</strong><span>Canonical record powers all views</span></div></div></>}
  {tab==="Schema"&&<div className="panel canonicalSchema"><div className="schemaHead"><Database size={16}/><strong>Canonical record fields</strong><span>Single source of truth</span></div>{canonicalFields.map(x=><div className="schemaRow" key={x[1]}><strong>{x[0]}</strong><code>{x[1]}</code><span>{x[2]}</span></div>)}<div className="schemaRule"><LockKeyhole size={15}/><p>Public and Executive views read from the same verified entities. Internal notes, review signals and unpublished research remain permission-controlled.</p></div></div>}
  {tab==="Runs"&&<div className="panel runHistory"><div className="runHead"><span>Run</span><span>Source</span><span>Found</span><span>Candidates</span><span>Matched</span><span>Review</span><span>Status</span><span>Time</span></div>{ingestionRuns.map(r=><div className="runRow" key={r.id}><b>{r.id}</b><strong>{r.source}</strong><span>{r.found}</span><span>{r.candidates}</span><span>{r.matched}</span><span>{r.review}</span><em>{r.status}</em><span>{r.time}</span></div>)}</div>}
  <div className="foundationRules"><div><ShieldCheck/><strong>No invented fields</strong><span>Unavailable values stay empty until sourced.</span></div><div><GitMerge/><strong>No silent entity merges</strong><span>Fuzzy matching proposes; verification confirms.</span></div><div><Database/><strong>Write once</strong><span>Verified canonical data propagates across Projects, Contractors and Executive.</span></div><div><CheckCircle2/><strong>Full provenance</strong><span>Every published field retains its source lineage.</span></div></div>
 </section>
}