"use client";
import {useState} from "react"; import {Database,Clock3,RefreshCw,Archive,ShieldCheck,AlertTriangle,CheckCircle2,Search,GitMerge} from "lucide-react"; import {backfillYears,nptaFields,nptaSchedule} from "@/data/nptaBackfill";
export default function NptaIngestion(){const [mode,setMode]=useState("Monitor");return <section><div className="nptaIntro"><div><span className="eyebrow green">PHASE 7.1 · PROCUREMENT INGESTION</span><h2>NPTA Contract Ingestion</h2><p>Live-monitoring design plus a controlled 2012→current historical backfill for awarded government contracts.</p></div><div className="nptaHealthy"><CheckCircle2 size={14}/> ADAPTER IMPLEMENTED · DEPLOYMENT REQUIRED</div></div>
<div className="nptaBoundary"><AlertTriangle size={15}/><p><strong>Connection boundary:</strong> the server-side NPTA parser, deduplication logic and backfill workflow are implemented here. A persistent database and deployed scheduled worker are still required before scans run automatically.</p></div>
<div className="nptaTabs"><button className={mode==="Monitor"?"active":""} onClick={()=>setMode("Monitor")}>Continuous Monitoring</button><button className={mode==="Backfill"?"active":""} onClick={()=>setMode("Backfill")}>2012–Present Backfill</button><button className={mode==="Mapping"?"active":""} onClick={()=>setMode("Mapping")}>Field Mapping</button></div>
{mode==="Monitor"&&<div className="nptaMonitorGrid"><div className="panel nptaSchedule"><div className="nptaCardHead"><Clock3/><strong>Scan schedule</strong></div><div><span>NORMAL</span><strong>{nptaSchedule.normal}</strong><small>Incremental scan for new or changed awards</small></div><div><span>HIGH-FREQUENCY</span><strong>{nptaSchedule.highFrequency}</strong><small>Temporary administrator override</small></div><div><span>HISTORICAL</span><strong>{nptaSchedule.historical}</strong></div></div>
<div className="panel nptaFlow"><div className="nptaCardHead"><RefreshCw/><strong>Scheduled run</strong></div>{[["1","Fetch","Read awarded-contract source"],["2","Parse","Extract structured NPTA fields"],["3","Deduplicate","Ignore unchanged records"],["4","Resolve","Match contractor, agency and project"],["5","Review","Route uncertain matches to Extraction Center"],["6","Publish","Verified record updates connected views"]].map(x=><div className="nptaStep" key={x[0]}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></div>)}</div>
<div className="panel nptaPropagation"><div className="nptaCardHead"><GitMerge/><strong>After verification</strong></div>{["Contractor Search","Contract history","Projects & Promises","Executive Intelligence","Connected Records","Source provenance"].map(x=><div key={x}><CheckCircle2/><span>{x}</span></div>)}</div></div>}
{mode==="Backfill"&&<><div className="backfillSummary"><div><Archive/><span><strong>2012 → Current</strong><small>Target repository window</small></span></div><div><Database/><span><strong>Coverage by year</strong><small>Measured, not assumed</small></span></div><div><ShieldCheck/><span><strong>Source-backed</strong><small>No unsupported completeness claim</small></span></div></div><div className="panel backfillTable"><div className="backfillHead"><span>Year</span><span>Status</span><span>Coverage</span><span>Discovered</span><span>Imported</span><span>Review</span></div>{backfillYears.map(y=><div className="backfillRow" key={y.year}><strong>{y.year}</strong><em>{y.status}</em><span>{y.coverage}</span><span>{y.discovered||"—"}</span><span>{y.imported||"—"}</span><span>{y.review||"—"}</span></div>)}</div><div className="backfillRule"><Search size={14}/><p>If older awards are absent from the current NPTA table, historical collection expands to archived official pages, procurement reports and other official records, each with its own provenance and coverage score.</p></div></>}
{mode==="Mapping"&&<div className="panel nptaMapping"><div className="mappingHead"><span>NPTA field</span><span>Canonical destination</span><span>Behavior</span></div>{nptaFields.map((f,i)=><div className="mappingRow" key={f}><strong>{f}</strong><code>{["agency_id","contract_id","contractor_id","description","amount","currency","procurement_method","tender_count","award_date","source_upload_date"][i]}</code><span>{i===2?"Normalize + fuzzy match; never silently merge":i===8?"Use source date exactly":"Preserve source value + provenance"}</span></div>)}</div>}</section>}