"use client";
import {useMemo,useState} from "react";
import {Search,Landmark,WalletCards,FileText,Building2,CalendarDays,MapPin,ShieldCheck,AlertTriangle,Link2,Clock3,CheckCircle2} from "lucide-react";
import {unifiedProjects} from "@/data/unifiedProjects";
import {realContracts} from "@/data/realContracts";
const Empty=({label})=><div className="chainEmpty"><span>{label}</span><strong>Not yet identified</strong><small>Awaiting a verified source</small></div>;
export default function UnifiedProjectsTracker(){
 const [selectedId,setSelectedId]=useState(unifiedProjects[0]?.id),[q,setQ]=useState(""),[year,setYear]=useState("2012"),[agency,setAgency]=useState("All"),[type,setType]=useState("All");
 const agencies=["All",...new Set(unifiedProjects.map(x=>x.agency))],types=["All",...new Set(unifiedProjects.map(x=>x.recordType))];
 const rows=useMemo(()=>unifiedProjects.filter(x=>(year==="All"||String(x.year)===year)&&(agency==="All"||x.agency===agency)&&(type==="All"||x.recordType===type)&&(`${x.title} ${x.agency} ${x.region} ${x.projectCode}`.toLowerCase().includes(q.toLowerCase()))),[q,year,agency,type]);
 const selected=unifiedProjects.find(x=>x.id===selectedId)||rows[0]||unifiedProjects[0],total=rows.reduce((a,x)=>a+x.budgetM,0);
 return <section className="unifiedTracker"><div className="unifiedTop"><div><span className="eyebrow green">UNIFIED PROJECT & PROMISE REPOSITORY</span><h1>Government Project & Promise Tracker</h1><p>Real source-backed records across budgets, projects, contracts, promises and delivery updates.</p></div><div className="verifiedBadge"><ShieldCheck size={14}/> SOURCE-BACKED DATA</div></div>
 <div className="repoMetrics"><div><strong>{rows.length}</strong><span>Records in view</span></div><div><strong>G${(total/1000).toFixed(2)}B</strong><span>Budget value represented</span></div><div><strong>{new Set(rows.map(x=>x.agency)).size}</strong><span>Entities in view</span></div><div><strong>2012</strong><span>Earliest loaded year</span></div></div>
 <div className="projectFilters"><div><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search project, agency, region or project code"/></div><select value={year} onChange={e=>setYear(e.target.value)}><option>All</option><option>2012</option></select><select value={agency} onChange={e=>setAgency(e.target.value)}>{agencies.map(x=><option key={x}>{x}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}>{types.map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="projectWorkspace"><div className="panel realProjectList"><div className="listTitle"><Landmark size={14}/><strong>Projects & Commitments</strong><span>{rows.length}</span></div>{rows.map(x=><button className={selected?.id===x.id?"selected":""} key={x.id} onClick={()=>setSelectedId(x.id)}><div><small>{x.year} · {x.projectCode}</small><em>{x.verification}</em></div><strong>{x.title}</strong><span><MapPin size={10}/>{x.region}</span><b>{x.budgetDisplay}</b></button>)}</div>
 {selected&&<div className="panel realProjectDetail"><div className="projectIdentity"><div><small>{selected.year} · {selected.projectCode} · {selected.recordType}</small><h2>{selected.title}</h2><p>{selected.agency}</p></div><em>{selected.verification}</em></div>
 <div className="projectFacts"><div><WalletCards/><span>Published budget</span><strong>{selected.budgetDisplay}</strong></div><div><CalendarDays/><span>Budget year</span><strong>{selected.year}</strong></div><div><MapPin/><span>Geography</span><strong>{selected.region}</strong></div><div><ShieldCheck/><span>Coverage</span><strong>Partial / expanding</strong></div></div>
 <div className="scopeBox"><FileText/><div><strong>OFFICIAL PROJECT / PROGRAMME DESCRIPTION</strong><p>{selected.scope}</p></div></div><h3>Promise · Budget · Project · Contract · Contractor</h3>
 <div className="realChain">{selected.promise?<div><Landmark/><span>Promise</span><strong>{selected.promise}</strong></div>:<Empty label="Promise"/>}<b>→</b><div className="chainVerified"><WalletCards/><span>Budget</span><strong>{selected.budgetDisplay}</strong><small>{selected.year} official estimate</small></div><b>→</b><div className="chainVerified"><FileText/><span>Project</span><strong>{selected.title}</strong><small>{selected.projectCode}</small></div><b>→</b>{selected.contractId?<div><FileText/><span>Contract</span><strong>{selected.contractId}</strong></div>:<Empty label="Contract"/>}<b>→</b>{selected.contractor?<div><Building2/><span>Contractor</span><strong>{selected.contractor}</strong></div>:<Empty label="Contractor"/>}</div>
 <div className="truthRule"><AlertTriangle size={13}/><span>A budget allocation proves the project/programme was budgeted. It does not by itself prove a contract award, contractor, completion status or delivery outcome.</span></div>
 <h3>Historical activity</h3><div className="realTimeline"><div><CheckCircle2/><span><strong>2012 budget record identified</strong><small>{selected.source} · page {selected.sourcePage}</small></span></div><div className="pending"><Clock3/><span><strong>Contract award</strong><small>Not yet identified from a verified procurement source</small></span></div><div className="pending"><Clock3/><span><strong>Delivery / completion evidence</strong><small>Awaiting linked official or independently verified source</small></span></div></div>
 <div className="sourceProof"><ShieldCheck/><div><strong>Source provenance</strong><span>{selected.source} · PDF page {selected.sourcePage}</span><small>{selected.coverage}</small></div></div></div>}
 <aside className="panel recordLegend"><h3>Record status</h3><div><i className="v"></i><span><strong>Verified Official Record</strong><small>Field supported by an official source.</small></span></div><div><i className="p"></i><span><strong>Partial Coverage</strong><small>Some relationships still need sources.</small></span></div><div><i className="e"></i><span><strong>Not yet identified</strong><small>No factual value is inferred.</small></span></div><div className="legendNote"><Link2/><p>Later procurement, promise and progress sources attach to this same project instead of creating disconnected duplicates.</p></div></aside></div><div className="currentProcurement"><h3>CURRENT PROCUREMENT REPOSITORY</h3><p>{realContracts.length} source-backed NPTA award records are loaded into Contractor Search. They remain separate from 2012 budget projects unless a verified project match is established.</p></div></section>
}