"use client";
import {useState} from "react"; import {Search,ShieldCheck,MapPin,Images,UserRound,CheckCircle2,XCircle,MessageSquareWarning,Clock3} from "lucide-react"; import {cases,audit} from "@/data/verification";
export default function VerificationCenter(){
 const [selected,setSelected]=useState(cases[0]),[filter,setFilter]=useState("All"); const statuses=["All","New","Under Review","Needs Evidence","Verified"],shown=cases.filter(x=>filter==="All"||x.status===filter);
 return <section><div className="verificationIntro"><div><span className="eyebrow green">PHASE 4 · STAFF OPERATIONS</span><h2>Verification Center</h2><p>Review citizen submissions before they enter the public accountability record.</p></div><div className="staffBadge"><ShieldCheck size={17}/> STAFF VIEW</div></div>
 <div className="staffMetrics">{[["18","New"],["11","Under review"],["7","Need evidence"],["24","Verified today"]].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div>
 <div className="verificationLayout"><div className="panel caseQueue"><div className="queueTop"><strong>Incoming reports</strong><div className="queueSearch"><Search size={14}/><input placeholder="Search cases"/></div></div><div className="statusTabs">{statuses.map(x=><button className={filter===x?"active":""} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div>{shown.map(c=><button key={c.id} onClick={()=>setSelected(c)} className={selected.id===c.id?"caseCard selected":"caseCard"}><div className="caseTop"><span>{c.id}</span><b className="caseStatus">{c.status}</b></div><strong>{c.title}</strong><small><MapPin size={11}/>{c.place} · {c.street}</small><div className="caseMeta"><span>{c.category}</span><span>{c.evidence} files</span><span>{c.severity}</span></div></button>)}</div>
 <div className="panel caseDetail"><div className="detailTop"><div><span className="eyebrow">{selected.id}</span><h3>{selected.title}</h3></div><b className="caseStatus">{selected.status}</b></div><div className="caseLocation"><MapPin size={17}/><div><strong>{selected.place}</strong><span>{selected.street} · {selected.lat}, {selected.lng}</span></div><button>Open map</button></div><div className="caseFacts">{[["Category",selected.category],["Severity",selected.severity],["Evidence",selected.evidence+" files"],["Possible duplicates",selected.duplicates]].map(x=><div key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div>
 <h4>Evidence preview</h4><div className="evidenceTiles">{[1,2,3].map(i=><div key={i}><Images/><span>{i<3?"Photo "+i:"More files"}</span></div>)}</div><h4>Verification checklist</h4><div className="checkList">{["Location is established","Evidence matches the issue","Duplicates reviewed / merged","Sensitive information reviewed","Severity is appropriate"].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div>
 <h4>Assignment & internal notes</h4><div className="assignment"><UserRound size={16}/><select defaultValue={selected.assignee}><option>Unassigned</option><option>Regional Review Team</option><option>Field Verification</option><option>Research Desk</option></select><textarea placeholder="Internal notes — never shown publicly."/></div><div className="reviewActions"><button className="needs"><MessageSquareWarning size={15}/> Need evidence</button><button className="reject"><XCircle size={15}/> Reject</button><button className="verify"><CheckCircle2 size={15}/> Verify report</button></div></div>
 <aside className="panel auditPanel"><div className="auditTitle"><Clock3 size={16}/><strong>Audit trail</strong></div>{audit.map((e,i)=><div className="auditEvent" key={i}><b>{e[0]}</b><span>{e[2]}</span><small>{e[1]}</small></div>)}<div className="auditNotice">Production will log every verification, severity, assignment, publication and resolution change with user and timestamp.</div></aside></div></section>
}